// Mock Agents
export const mockAgents = [
  {
    id: "agent1",
    name: "Sarah Johnson",
    email: "sarah.johnson@realestate.com",
    phone: "(123) 456-7890",
    photo: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "agent2",
    name: "Michael Chen",
    email: "michael.chen@realestate.com",
    phone: "(123) 456-7891",
    photo: "/placeholder.svg?height=200&width=200",
  },
  {
    id: "agent3",
    name: "Jessica Williams",
    email: "jessica.williams@realestate.com",
    phone: "(123) 456-7892",
    photo: "/placeholder.svg?height=200&width=200",
  },
]

// Mock Users
export const mockUsers = [
  {
    id: "buyer1",
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "(123) 456-7893",
    photo: "/images/placeholder.svg",
    savedProperties: ["prop1", "prop3"],
    role: "buyer",
  },
  {
    id: "seller1",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    phone: "(123) 456-7894",
    photo: "/images/placeholder.svg",
    savedProperties: [],
    listings: ["prop1", "prop2"],
    role: "seller",
  },
  {
    id: "seller2",
    name: "Robert Johnson",
    email: "robert.johnson@example.com",
    phone: "(123) 456-7895",
    photo: "/images/placeholder.svg",
    savedProperties: [],
    listings: ["prop3", "prop6"],
    role: "seller",
  },
  {
    id: "seller3",
    name: "Emily Davis",
    email: "emily.davis@example.com",
    phone: "(123) 456-7896",
    photo: "/images/placeholder.svg",
    savedProperties: [],
    listings: ["prop7", "prop8"],
    role: "seller",
  },
]

// Mock Properties - Removed all rent type properties
// export const mockPropertie = [
//   {
//     id: "prop1",
//     title: "Modern Downtown Apartment",
//     description:
//       "Luxurious 2-bedroom apartment in the heart of downtown with stunning city views, modern appliances, and access to premium amenities including a gym, pool, and rooftop terrace.",
//     price: 450000,
//     type: "sale",
//     bedrooms: 2,
//     bathrooms: 2,
//     squareFeet: 1200,
//     location: "123 Main St, New York, NY",
//     sellerId: "seller1",
//     images: [
//       "/images/placeholder.svg",
//       "/images/placeholder.svg",
//       "/images/placeholder.svg",
//     ],
//     features: ["Hardwood Floors", "Central AC", "In-unit Laundry", "Balcony", "Parking"],
//     yearBuilt: 2018,
//     agent: mockAgents[0],
//     reviews: [
//       {
//         id: "rev1",
//         userId: "user1",
//         userName: "John Doe",
//         rating: 4,
//         comment: "Great property, excellent location!",
//         date: "2023-05-15",
//       },
//     ],
//   },
//   {
//     id: "prop2",
//     title: "Spacious Family Home",
//     description:
//       "Beautiful 4-bedroom family home in a quiet suburban neighborhood with a large backyard, updated kitchen, and finished basement.",
//     price: 750000,
//     type: "sale",
//     bedrooms: 4,
//     bathrooms: 3,
//     squareFeet: 2800,
//     location: "456 Oak Ave, Chicago, IL",
//     sellerId: "seller1",
//     images: [
//       "/images/placeholder.svg",
//       "/images/placeholder.svg",
//       "/images/placeholder.svg",
//     ],
//     features: ["Finished Basement", "Backyard", "Garage", "Fireplace", "Updated Kitchen"],
//     yearBuilt: 2005,
//     agent: mockAgents[1],
//   },
//   {
//     id: "prop3",
//     title: "Luxury Waterfront Condo",
//     description:
//       "Stunning 3-bedroom waterfront condo with panoramic ocean views, high-end finishes, and resort-style amenities.",
//     price: 1200000,
//     type: "sale",
//     bedrooms: 3,
//     bathrooms: 3.5,
//     squareFeet: 2200,
//     location: "789 Beach Blvd, Miami, FL",
//     sellerId: "seller2",
//     images: [
//       "/images/placeholder.svg",
//       "/images/placeholder.svg",
//       "/images/placeholder.svg",
//     ],
//     features: ["Ocean View", "Private Balcony", "Concierge", "Pool", "Gym"],
//     yearBuilt: 2020,
//     agent: mockAgents[2],
//   },
//   {
//     id: "prop6",
//     title: "Rustic Mountain Cabin",
//     description: "Charming 2-bedroom cabin nestled in the mountains with stunning views and a cozy fireplace.",
//     price: 350000,
//     type: "sale",
//     bedrooms: 2,
//     bathrooms: 1,
//     squareFeet: 1100,
//     location: "333 Mountain Rd, Denver, CO",
//     sellerId: "seller2",
//     images: [
//       "/images/placeholder.svg",
//       "/images/placeholder.svg",
//       "/images/placeholder.svg",
//     ],
//     features: ["Mountain Views", "Fireplace", "Wood Floors", "Large Deck"],
//     yearBuilt: 1985,
//     agent: mockAgents[2],
//   },
//   {
//     id: "prop7",
//     title: "Contemporary Urban Loft",
//     description: "Stylish loft in the arts district with high ceilings, exposed brick, and modern finishes.",
//     price: 525000,
//     type: "sale",
//     bedrooms: 1,
//     bathrooms: 1.5,
//     squareFeet: 1050,
//     location: "555 Artist Way, Portland, OR",
//     sellerId: "seller3",
//     images: [
//       "/images/placeholder.svg",
//       "/images/placeholder.svg",
//       "/images/placeholder.svg",
//     ],
//     features: ["High Ceilings", "Exposed Brick", "Open Floor Plan", "Stainless Appliances"],
//     yearBuilt: 2008,
//     agent: mockAgents[0],
//   },
//   {
//     id: "prop8",
//     title: "Suburban Ranch Home",
//     description: "Well-maintained ranch home on a corner lot with updated kitchen and bathrooms.",
//     price: 425000,
//     type: "sale",
//     bedrooms: 3,
//     bathrooms: 2,
//     squareFeet: 1800,
//     location: "777 Maple Street, Austin, TX",
//     sellerId: "seller3",
//     images: [
//       "/images/placeholder.svg",
//       "/images/placeholder.svg",
//       "/images/placeholder.svg",
//     ],
//     features: ["Corner Lot", "Updated Kitchen", "Patio", "Attached Garage"],
//     yearBuilt: 1995,
//     agent: mockAgents[1],
//   },
// ]

export const mockProperties = [
  {
    id: 1,
    Title: "'Horizons', Banna East, Ardfert, Banna, Co. Kerry, V92HT65",
    Price: 499000,
    NoOfBedrooms: 4,
    NoOfBathrooms: 6,
    PropertyType: "Detached",
    FloorArea: 247,
    BERRating: "B3",
    Latitude: 52.359776,
    Longitude: 9.797407,
    ListingViews: 3558,
    sellerId: "seller1",
    agent: mockAgents[0],
    Area: "banna-kerry",
    County: "Kerry",
    Features: "Sea/Mountain/Countryside Views, Equal distance between Banna Beach & Ballyheigue Beach, Exceptional finish throughout, Stunning Garden/Oasis, Electric Gate, Currently incorporates a self contained apartment/granny flat, BER B3, 20 Min walk to Blackrock Beach, Windows Replaced approx 3 years ago, Large, wide spaces and hallway would allow ease of access for persons with mobility issues.",
    DateOfConstruction: "NA",
    image1: "https://photos.zillowstatic.com/fp/95a90a05dfd2ea80469d906339734e0e-p_e.webp",
    image2: "https://photos.zillowstatic.com/fp/d9e2f8c5bb49bd7bde8b6fa43c0eb2ab-p_e.webp",
    image3: "https://photos.zillowstatic.com/fp/3c9e10348dffe50eb5dd24c29486e40f-p_e.webp"
  },
  {
    id: 2,
    Title: "Ivella, Rectory Road, Enniscorthy, Co. Wexford, Y21WN30",
    Price: 925000,
    NoOfBedrooms: 4,
    NoOfBathrooms: 3,
    PropertyType: "End of Terrace",
    FloorArea: 262,
    BERRating: "B3",
    Latitude: 52.359776,
    Longitude: 9.797407,
    ListingViews: 3558,
    sellerId: "seller2",
    agent: mockAgents[1],
    Area: "enniscorthy-wexford",
    County: "Wexford",
    Features: "Exceptionally well-presented heritage property, Refurbished in 2014 to perfecting standards, 4 bedrooms, 3 bathrooms, Extending to c. 262 sq.m. , Separate studio apartment",
    DateOfConstruction: "NA",
    image1: "https://photos.zillowstatic.com/fp/3526534c31af1a257ee10411ca155239-p_e.webp",
    image2: "https://photos.zillowstatic.com/fp/c4b6a1dc5e03940b1879d00bc9781a9a-p_e.webp",
    image3: "https://photos.zillowstatic.com/fp/36764305980d0294b0cc56f177dbb7f5-p_e.webp"
  },
  {
    id: 3,
    Title: "Grey's Corner, Ferrybank, Co. Wexford, Y35XNP4",
    Price: 895000,
    NoOfBedrooms: 5,
    NoOfBathrooms: 2,
    PropertyType: "Detached",
    FloorArea: 265,
    BERRating: "B3",
    Latitude: 52.3486,
    Longitude: 6.456929,
    ListingViews: 14011,
    sellerId: "seller3",
    agent: mockAgents[2],
    Area: "ferrybank-wexford",
    County: "Wexford",
    Features: "Overlooking the River Slaney Estuary & Wexford town.  , Built in 2007 , Extending to c. 265 sq.m. / 2,853 sq.ft. , 5 bedrooms, 2 bathrooms., Private & sheltered patio facing the river estuary view.",
    DateOfConstruction: 2007,
    image1: "https://photos.zillowstatic.com/fp/fc282c473c8b32fea61217d3e68112b1-p_e.webp",
    image2: "https://photos.zillowstatic.com/fp/15be7540f7d0d584967ed3794b4ef84f-p_e.webp",
    image3: "https://photos.zillowstatic.com/fp/3b94dbf67647f99a6fe3e03a4689932b-p_e.webp"
  },
  {
    id: 4,
    Title: "Lindon Lodge, Luddenmore, Ballyneety, Co. Limerick, V35EE76",
    Price: 445000,
    NoOfBedrooms: 5,
    NoOfBathrooms: 2,
    PropertyType: "Detached",
    FloorArea: 0.5,
    BERRating: "D1",
    Latitude: 52.5708405,
    Longitude: -8.5358043,
    ListingViews: 2422,
    sellerId: "seller1",
    agent: mockAgents[0],
    Area: "ballyneety-limerick",
    County: "Limerick",
    Features: "Built in 1978, Circa 192 sq.m., Stands on Circa 0.50 acre site, 10 minute commute Limerick City, Pantry & Utility, 2 Reception rooms, Attached Garage, O.F.C.H, Landscaped Lawns, Close to all amenities",
    DateOfConstruction: "NA",
    image1: "https://photos.zillowstatic.com/fp/72fd8324c0fa7fd8fe71d670e9f7e0a7-p_e.webp",
    image2: "https://photos.zillowstatic.com/fp/2533c39da15247e580fd4a5494216f99-p_e.webp",
    image3: "https://photos.zillowstatic.com/fp/a024686584e44844901df96d0b9a0759-p_e.webp"
  },
  {
    id: 5,
    Title: "Ballard, Barna, Co. Galway, H91P22T",
    Price: 1250000,
    NoOfBedrooms: 4,
    NoOfBathrooms: 4,
    PropertyType: "Detached",
    FloorArea: 333,
    BERRating: "D2",
    Latitude: 53.257378,
    Longitude: -9.134137,
    ListingViews: 19535,
    Area: "barna-galway",
    sellerId: "seller2",
    agent: mockAgents[1],
    County: "Galway",
    Features: "",
    DateOfConstruction: 1978,
    image1: "https://photos.zillowstatic.com/fp/18a631f3c08c324e658b0e26ea4ce2cb-p_e.webp",
    image2: "https://photos.zillowstatic.com/fp/efdfa00cd92338dd5240be5f2dbef6f0-p_e.webp",
    image3: "https://photos.zillowstatic.com/fp/7eb6bfddb88ae784b17445bbf193f405-p_e.webp"
  },
  {
    id: 6,
    Title: "11 Birchfield Lawn, Dublin 14, Kilmacud, Co. Dublin, D14R6C5",
    Price: 595000,
    NoOfBedrooms: 4,
    NoOfBathrooms: 1,
    PropertyType: "Semi-D",
    FloorArea: 93,
    BERRating: "D1",
    Latitude: 53.291674,
    Longitude: 6.23159,
    ListingViews: 4565,
    sellerId: "seller3",
    agent: mockAgents[2],
    Area: "kilmacud-dublin",
    County: "Dublin",
    Features: "Four bed home in a prime location - 93sqms / 1000 sq. ft., Off street parking, Superb local schools, Gas fired central heating., Enjoy access to local amenities parks, and public transport., All fitted carpets, curtains, light fittings, and kitchen appliances are included., Quiet yet highly convenient location",    
    DateOfConstruction: 1983,    
    image1: "https://photos.zillowstatic.com/fp/8a9fce96b937520ae867575dd700d0f4-p_e.webp",
    image2: "https://photos.zillowstatic.com/fp/7d70e627b34c2ee37e1b621b1d6fb09f-p_e.webp",
    image3: "https://photos.zillowstatic.com/fp/ae94527a7a08b391c3b362fd4fe417a6-p_e.webp"
  },
]